name: 'Add Labels'
description: 'Add labels to issues or PRs'
author: 'Microsoft'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  labels:
    description: 'Labels to add to this issue or PR'
runs:
  using: 'node12'
  main: 'lib/main.js'
